





```{r}
library(sf)
library(sp)
library(nngeo)
```

```{r}
ibra <- st_read("/Users/61487/Documents/GrevBuxi_complex/IBRA_V7_Subregions/Interim_Biogeographic_Regionalisation_for_Australia_(IBRA)_Version_7_(Subregions).shp")

clpr <- ibra[ibra$SUB_NAME_7=="Cumberland",]

```

```{r}

sites <- as.data.frame(dmv_DF) %>% 
  group_by(site) %>%
  reframe(av_lat=mean(as.numeric(lat)), av_long=mean(as.numeric(long)))

pw_sites <- sites %>%
  setNames(paste0(names(.), '_2')) %>%
  crossing(sites)

pw_sites[2,]
divxlims <- c(min(filtered_site_summary$long, na.rm=TRUE)-0.1,
              max(filtered_site_summary$long, na.rm=TRUE)+0.1) #find the min / max longitude
divylims <- c(min(filtered_site_summary$lat, na.rm=TRUE)-0.1,
              max(filtered_site_summary$lat, na.rm=TRUE)+0.1)

bbox <- st_bbox(c(xmin = min(filtered_site_summary$long, na.rm=TRUE)-0.1, xmax = max(filtered_site_summary$long, na.rm=TRUE)+0.1, ymax = min(filtered_site_summary$lat, na.rm=TRUE)-0.1, ymin = max(filtered_site_summary$lat, na.rm=TRUE)+0.1), crs = st_crs(3107))


clpr  <- clpr %>% st_set_crs(3107)
sq_grid_sample <- st_sample(st_as_sfc(st_bbox(bbox)), size = 1000, type = 'regular') %>% st_as_sf() %>%
  st_connect(.,.,k = 9)

sq_grid_cropped <- sq_grid_sample[st_within(sq_grid_sample, clpr$geometry, sparse = F),]


plot(bbox)
plot(clpr$geometry)
plot(sq_grid_sample)










# sample the bounding box with regular square points, then connect each point to the closest 9 points
#  8 should've worked, but left some diagonals out.
sq_grid_sample <- st_sample(st_as_sfc(st_bbox(moose_lake)), size = 1000, type = 'regular') %>% st_as_sf() %>%
  st_connect(.,.,k = 9)

# remove connections that are not within the lake polygon
sq_grid_cropped <- sq_grid_sample[st_within(sq_grid_sample, moose_lake, sparse = F),]

# make an sfnetwork of the cropped grid
lake_network <- sq_grid_cropped %>% as_sfnetwork()

# find the (approximate) distance from boat ramp to point 170 (far north)
pt170 <- st_network_paths(lake_network, 
                          from = boat_ramp,
                          to = sample_locations[170,]) %>%
  pull(edge_paths) %>%
  unlist()

lake_network %>% 
  activate(edges) %>%
  slice(pt170) %>%
  st_as_sf() %>%
  st_combine() %>%
  st_length()
#> 2186.394 [m]
#> 
#> 
#> 
#> 
#> 
#> 
#> 

# Getting your data:
x <- dget("https://raw.githubusercontent.com/BajczA475/random-data/main/Moose.lake")
# Subset to get just one lake
moose_lake <- x[5,]
boat_ramp <- dget("https://raw.githubusercontent.com/BajczA475/random-data/main/Moose.access")
sample_locations <- dget("https://raw.githubusercontent.com/BajczA475/random-data/main/Moose.ssw")
sample_bbox <- dget("https://raw.githubusercontent.com/BajczA475/random-data/main/Moose.box")
sample_bbox
```


